package org.fuzzydb.spring.repository;

import org.fuzzydb.attrs.userobjects.IdFieldMappedFuzzyItem;
import org.fuzzydb.client.DataOperations;
import org.fuzzydb.client.Ref;
import org.fuzzydb.client.exceptions.UnknownObjectException;

/**
 * Deals with the persisting of native fuzzydb objects where they are
 * identified by an indexed id field, and have therefore been mapped into
 * IdFieldMappedFuzzyItem
 *
 * @param <ID> Comparable that *must* be generated by the application for
 * the id used to store and retrieve (e.g. could be UUID, ObjectId)
 */
public final class IndexedIdPersistenceStrategy<ID> implements
		PersistByIdPersistenceStrategy<ID, IdFieldMappedFuzzyItem> {

	private final String nativeIdField = "id";
	private final Class<IdFieldMappedFuzzyItem> internalType = IdFieldMappedFuzzyItem.class;
	private final DataOperations persister;

	public IndexedIdPersistenceStrategy(DataOperations persister) {
		this.persister = persister;
	}

	@Override
	public boolean exists(ID id) {
		return findEntityById(id) != null;
	}

	@Override
	public IdFieldMappedFuzzyItem findEntityById(ID id) {
		IdFieldMappedFuzzyItem entity;
		try {
			entity = persister.retrieve(internalType, nativeIdField, (Comparable<?>)id);
		} catch (UnknownObjectException e) {
			return null;
		}
		return entity;
	}

	@Override
	public final Ref<IdFieldMappedFuzzyItem> toInternalId(ID id) {
		IdFieldMappedFuzzyItem item = findEntityById(id);
		return persister.getRef(item);
	}

	@Override
	public ID toExternalId(Ref<IdFieldMappedFuzzyItem> ref) {
		return null;  // Return null and let entity converter do it
	}

	@Override
	public ID saveOrUpdate(IdFieldMappedFuzzyItem entity, ID existingRef) {
		if (existingRef != null) {
			// already supplied, so either insert with ID or is merge
			IdFieldMappedFuzzyItem existing = findEntityById(existingRef);
			// Merge of exising
			if (existing != null) {
				existing.mergeFrom(entity);
				persister.update(existing);
				return existingRef;
			}
		}
		// New entity
		Ref<IdFieldMappedFuzzyItem> ref = persister.save(entity);
		return toExternalId(ref);
	}
}